# Generated by Django 5.2.5 on 2025-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('tecnico', 'Técnico'), ('dev', 'Desenvolvedor')], default='gestor', max_length=20),
        ),
    ]
