# Generated by Django 5.2.5 on 2025-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_senha_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('tecnico', 'Técnico'), ('dev', 'Desenvolvedor')], default='gestor', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='123456', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
